### ISSUE TITLE
Eye tracking features to implement

### ISSUE THREAD

**Issue by HemuManju** [iHuman-Lab/igaze#1]
-  [x] Blink Rate
- [x] Pupil Dilation
- [x] Fixation Rate
- [x] Fixation Count
- [x] Fixation Time in AOI
- [x] % Time Spent in an AOI
- [x] Dwell Time
- [x] Dwell Count (Look Rate)
- [x] Turn Rate
- [x] Saccade Amplitude
- [x] Saccade Frequency
- [x] Run Count
- [x] Nearest Neighbor Index or Entropy
- [x] Fixation Location Derived Index
- [x] Gaze Hit Rate
